config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  scope '/games' do
    get '/space_garbage_warrior_2988', to: 'games#space_garbage_warrior', as: 'space_garbage_warrior'
    get '/homebreaker', to: 'games#homebreaker', as: 'homebreaker'
    get '/maggie', to: 'games#maggie', as: 'maggie'
    get '/immortal_legion', to: 'games#immortal_legion', as: 'immortal_legion'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def space_garbage_warrior; end

  def homebreaker; end

  def maggie
    @images = Dir.glob("public/images/maggie/*.gif")
  end

  def immortal_legion
    render layout: 'immortal_legion'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index; end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/homebreaker.html.slim
#homebreaker
= javascript_include_tag \
  'phaser.min',
  'homebreaker'

app/views/games/immortal_legion.html.slim
.body-copy
  .title
    .image-block
      = image_tag 'banner.png', class: 'banner'
    .image-block
      h1 Immortal Legion
    .image-block
      = image_tag 'banner.png', class: 'banner'
  = image_tag 'imperator.jpg', class: 'imperator-kill'

  .col-2
    .news
      h2 NEWS
      ul
        li= link_to '1/31/15: HEROIC IMPERATOR DED!!!!!', 'https://www.youtube.com/watch?v=4Qq1I6Z7lYk'
        li 1/14/15: DETHROGEN IS kewl :)
        li 1/1/15: HAPPY NEW YEAR!!!!!!!!!!!!!
        li 12/27/14: GUILD STARTED!
  .col-2
    .news
      h2 ROSTER
      ul
        li GM: LAC
        li CO-GM: fuzzy-i-never-talk-wuzzy
        li RAID LEADER: mechasneeze
        li TANK: philadelphia
        li #1 PLAYER: Dethrogen
        li #2 PLAYER: Dapoopie
        li funny voice guy: ice
        li everyone else: everyone else
  .forums
    h2 FORUMS
    table
      tr
        td Title
        td Author
        td Date
        td Content
      tr
        td HEROIC IMP!
        td Dethrogen
        td 1/31/15
        td AMAZING WORK last night guys seriously great job. We really need to...
      tr
        td Dave
        td Lac
        td 1/24/15
        td Do you think margaritas are...
      tr
        td Why doesn't dadoopie ever talk?
        td Mechanize
        td 1/12/15
        td Seriously guys it's so weird I don't even get it like why does she...
      tr
        td Politics
        td Cincinnati
        td 12/31/14
        td So after drinking a gallon of beer I came to the conclusion last night...

  = image_tag 'dwarf.gif', class: 'dwarf'
  = image_tag 'dwarf.gif', class: 'dwarf'
  = image_tag 'dwarf.gif', class: 'dwarf'
  = image_tag 'dwarf.gif', class: 'dwarf'
  = image_tag 'dwarf.gif', class: 'dwarf'

app/views/games/maggie.html.slim
#photos
  - 3.times do
    - @images.each do |image|
      = image_tag "maggie/#{image.split('/').last}"

app/views/games/space_garbage_warrior.html.slim
#spacegarbagewarrior2988
= javascript_include_tag \
  'phaser.min',
  'space-garbage-warrior'

app/views/home/index.html.slim
.container
  h1.site__heading Tim Minkov

  ul.site__nav
    li= link_to 'Teespring', 'http://teespring.com'
    li= link_to 'Github', 'http://github.com/timminkov'
    li= link_to 'Linkedin', 'https://www.linkedin.com/pub/tim-minkov/22/171/502'
    li= link_to 'Twitter', 'http://twitter.com/timminkov'

  .piece
    h3 Escape From Tethys
    = image_tag 'escapefromtethys.jpg'
    p Metroidvania released on Steam. I did programming/design.
    = link_to 'View online', 'https://store.steampowered.com/app/822540/Escape_From_Tethys/'

  .piece
    h3 Should I Watch...
    = image_tag 'shouldiwatch.png'
    p Simple app that compiles Rotten Tomatoes, IMDB, and metacritic ratings to deliver a weighted average and recommendation. Made using EmberJS (and CLI).
    = link_to 'View online', 'http://shouldi.watch'
    = link_to 'Github', 'http://github.com/timminkov/should-i-watch'

  .piece
    h3 Gather Your Party
    = image_tag 'gyp.png'
    p Wordpress gaming journalism site. I wrote some JS and helped with code-cleanup.
    = link_to 'View online', 'http://gatheryourparty.com'
    = link_to 'Github', 'http://github.com/Catsman/GatherYourPartium'

  .piece
    h3 Space Garbage Warrior 2888
    = image_tag 'spacegarbage.png'
    p Made for blitit game jam in 2014 using Phaser. Never finished.
    = link_to 'Play', space_garbage_warrior_path
    = link_to 'Github', 'http://github.com/timminkov/space-garbage-warrior-2988'

  .piece
    h3 Homebreaker
    = image_tag 'homebreaker.png'
    p Tagjam14 project. The idea was to rob houses using shadows. The first house was supposed to be a surprise party.
    = link_to 'Play', homebreaker_path
    = link_to 'Github', 'http://github.com/timminkov/homebreaker'

  .piece
    h3 MaggieWall
    = image_tag 'maggiewall.png'
    p ...
    = link_to 'View online', maggie_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimmiT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/immortal_legion.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimmiT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body style='background-color: black'>

<%= yield %>

</body>
</html>